### ISSUE TITLE
Jak zmienić bazę danych

### ISSUE THREAD

**Issue by Jamsson** [Nasus20202/AspShop#20]
Próbowałem dzisiaj zmienić bazę danych na PostgreSql i na mongodb, na początku poprosiłem gpt o pomoc i nadal dawał błąd, byłbym bardzo wdzięczny, gdybyś mógł mi pomóc ze zmianą bazy danych

**Comment by Nasus20202** [comment]
You have to replace the `Microsoft.EntityFrameworkCore.Sqlite` package with its equivalent for Postgresql or MongoDB  in the [ShopWebApp.csproj](https://github.com/Nasus20202/AspShop/blob/master/ShopWebApp.csproj) file. Then you just have to configure the database connection in the [ShopDatabase.cs](https://github.com/Nasus20202/AspShop/blob/master/Database/ShopDatabase.cs) file. You can also look at the older versions of this project which were using MySQL instead of SQLite. That should be it, if you have any other issue, feel free to reach out :).

**Comment by Jamsson** [comment]
Thanks for your help, another question is, what to do to make the site appeared products and their descriptions and all that is associated with it, just as I realized in the repository is not all folders and files.

**Comment by Jamsson** [comment]
I forgot to ask how to get into the admin panel, if it depends a lot on the database I use local PostgreSql
